---
language: node_js
node_js:
  - "0.12"

sudo: false

addons:  
  firefox: latest

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

after_success:
  - ember surge

script:
  - ember try $EMBER_TRY_SCENARIO test
