---
language: node_js
node_js:
  - "6.11.3"

sudo: false

addons:  
  firefox: latest

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta

services:
  - xvfb

before_install:
  - export DISPLAY=:99.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - npm install -g surge

install:
  - npm install -g bower
  - npm install
  - bower install

after_success:
  - surge ./dist/ ember-blockly.surge.sh

script:
  - ember try $EMBER_TRY_SCENARIO test
